[versions]
# Kotlin
kotlin = "2.2.0"

# Android
android-gradle-plugin = "8.2.0"

# Gradle plugins
gradle-plugin-publish = "1.2.1"
ktlint = "12.1.0"

# Testing
junit-jupiter = "5.10.0"
mockito = "5.1.1"
mockito-kotlin = "5.1.0"
mockk = "1.13.8"

# Java
java = "21"

[libraries]
# Kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }

# Testing
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
# Kotlin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

# Android
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }

# Gradle plugins
java-gradle-plugin = { id = "java-gradle-plugin" }
maven-publish = { id = "maven-publish" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-plugin-publish" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

[bundles]
# Test bundles
test = ["junit-jupiter", "mockito-core", "mockito-junit-jupiter", "mockito-kotlin", "mockk"]
kotlin-test = ["kotlin-test", "kotlin-test-junit5"]
