name: Publish Gradle Plugin

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Gradle
      uses: ./.github/actions/setup-gradle

    - name: Run Tests
      uses: ./.github/actions/run-tests

  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Pre-commit
      uses: ./.github/actions/run-pre-commit

  publish:
    needs: [test, pre-commit]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/setup-gradle

      - name: Publish plugin
        run: ./gradlew :plugin:publishPlugins
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
